# Generated by Django 4.2.1 on 2023-05-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Request'),
        ),
    ]
